/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3 */

#ifndef PB_DEF_PB_H_INCLUDED
#define PB_DEF_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _OdomReport {
    float pos_x;
    float pos_y;
    float pos_theta;
} OdomReport;

typedef struct _SpeedCommand {
    float vx;
    bool has_vy;
    float vy;
    float vtheta;
} SpeedCommand;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SpeedCommand_init_default                {0, false, 0, 0}
#define OdomReport_init_default                  {0, 0, 0}
#define SpeedCommand_init_zero                   {0, false, 0, 0}
#define OdomReport_init_zero                     {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define OdomReport_pos_x_tag                     1
#define OdomReport_pos_y_tag                     2
#define OdomReport_pos_theta_tag                 3
#define SpeedCommand_vx_tag                      1
#define SpeedCommand_vy_tag                      2
#define SpeedCommand_vtheta_tag                  3

/* Struct field encoding specification for nanopb */
#define SpeedCommand_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    vx,                1) \
X(a, STATIC,   OPTIONAL, FLOAT,    vy,                2) \
X(a, STATIC,   REQUIRED, FLOAT,    vtheta,            3)
#define SpeedCommand_CALLBACK NULL
#define SpeedCommand_DEFAULT NULL

#define OdomReport_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    pos_x,             1) \
X(a, STATIC,   REQUIRED, FLOAT,    pos_y,             2) \
X(a, STATIC,   REQUIRED, FLOAT,    pos_theta,         3)
#define OdomReport_CALLBACK NULL
#define OdomReport_DEFAULT NULL

extern const pb_msgdesc_t SpeedCommand_msg;
extern const pb_msgdesc_t OdomReport_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SpeedCommand_fields &SpeedCommand_msg
#define OdomReport_fields &OdomReport_msg

/* Maximum encoded size of messages (where known) */
#define SpeedCommand_size                        15
#define OdomReport_size                          15

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
